name: FTP Deploy to cyberex.com.tr

on:
  workflow_dispatch:
    inputs:
      ftp_server:
        description: 'FTP Server'
        required: true
        default: 'cyberex.com.tr'
      ftp_username:
        description: 'FTP Username'
        required: true
      ftp_password:
        description: 'FTP Password'
        required: true
        type: password

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Deploy to FTP
        uses: SamKirkland/FTP-Deploy-Action@4.3.0
        with:
          server: ${{ inputs.ftp_server }}
          username: ${{ inputs.ftp_username }}
          password: ${{ inputs.ftp_password }}
          local-dir: ./web/
          server-dir: /public_html/web3app/

